package com.csi0n.searchjob.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.csi0n.searchjob.database.dao.FuLi;
import com.csi0n.searchjob.database.dao.JobType;
import com.csi0n.searchjob.database.dao.City;
import com.csi0n.searchjob.database.dao.Area;

import com.csi0n.searchjob.database.dao.FuLiDao;
import com.csi0n.searchjob.database.dao.JobTypeDao;
import com.csi0n.searchjob.database.dao.CityDao;
import com.csi0n.searchjob.database.dao.AreaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fuLiDaoConfig;
    private final DaoConfig jobTypeDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig areaDaoConfig;

    private final FuLiDao fuLiDao;
    private final JobTypeDao jobTypeDao;
    private final CityDao cityDao;
    private final AreaDao areaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fuLiDaoConfig = daoConfigMap.get(FuLiDao.class).clone();
        fuLiDaoConfig.initIdentityScope(type);

        jobTypeDaoConfig = daoConfigMap.get(JobTypeDao.class).clone();
        jobTypeDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        fuLiDao = new FuLiDao(fuLiDaoConfig, this);
        jobTypeDao = new JobTypeDao(jobTypeDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        areaDao = new AreaDao(areaDaoConfig, this);

        registerDao(FuLi.class, fuLiDao);
        registerDao(JobType.class, jobTypeDao);
        registerDao(City.class, cityDao);
        registerDao(Area.class, areaDao);
    }
    
    public void clear() {
        fuLiDaoConfig.getIdentityScope().clear();
        jobTypeDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        areaDaoConfig.getIdentityScope().clear();
    }

    public FuLiDao getFuLiDao() {
        return fuLiDao;
    }

    public JobTypeDao getJobTypeDao() {
        return jobTypeDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

}
