package com.csi0n.searchjob.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FU_LI".
 */
public class FuLi {

    private int Fid;
    /** Not-null value. */
    private String name;

    private boolean isCheck=false;

    public FuLi() {
    }

    public FuLi(int Fid, String name) {
        this.Fid = Fid;
        this.name = name;
    }

    public int getFid() {
        return Fid;
    }

    public void setFid(int Fid) {
        this.Fid = Fid;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public boolean isCheck() {
        return isCheck;
    }

    public void setCheck(boolean check) {
        isCheck = check;
    }
}
