package com.csi0n.searchjob.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.csi0n.searchjob.database.dao.FuLi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FU_LI".
*/
public class FuLiDao extends AbstractDao<FuLi, Void> {

    public static final String TABLENAME = "FU_LI";

    /**
     * Properties of entity FuLi.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Fid = new Property(0, int.class, "Fid", false, "FID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    };


    public FuLiDao(DaoConfig config) {
        super(config);
    }
    
    public FuLiDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FU_LI\" (" + //
                "\"FID\" INTEGER NOT NULL ," + // 0: Fid
                "\"NAME\" TEXT NOT NULL );"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FU_LI\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FuLi entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getFid());
        stmt.bindString(2, entity.getName());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public FuLi readEntity(Cursor cursor, int offset) {
        FuLi entity = new FuLi( //
            cursor.getInt(offset + 0), // Fid
            cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FuLi entity, int offset) {
        entity.setFid(cursor.getInt(offset + 0));
        entity.setName(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(FuLi entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(FuLi entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
