package com.csi0n.searchjob.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "JOB_TYPE".
 */
public class JobType {

    private Integer Jid;
    private String name;

    public JobType() {
    }

    public JobType(Integer Jid, String name) {
        this.Jid = Jid;
        this.name = name;
    }

    public Integer getJid() {
        return Jid;
    }

    public void setJid(Integer Jid) {
        this.Jid = Jid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
